/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mp_rage_launcher_blip_BlipNative */

#ifndef _Included_mp_rage_launcher_blip_BlipNative
#define _Included_mp_rage_launcher_blip_BlipNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_blip_BlipNative_getType
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_blip_BlipNative_destroy
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getDimension
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_blip_BlipNative_getDimension
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    setDimension
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_blip_BlipNative_setDimension
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getPosition
 * Signature: (I)Lmp/rage/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_blip_BlipNative_getPosition
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    setPosition
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_blip_BlipNative_setPosition
        (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getRotation
 * Signature: (I)Lmp/rage/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_blip_BlipNative_getRotation
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    setRotation
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_blip_BlipNative_setRotation
        (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getModel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_blip_BlipNative_getModel
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    setModel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_blip_BlipNative_setModel
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getVelocity
 * Signature: (I)Lmp/rage/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_blip_BlipNative_getVelocity
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getAlpha
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_blip_BlipNative_getAlpha
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    setAlpha
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_blip_BlipNative_setAlpha
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getRadius
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_launcher_blip_BlipNative_getRadius
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_blip_BlipNative_getMode
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getColour
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_blip_BlipNative_getColour
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    setColour
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_blip_BlipNative_setColour
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getScale
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_launcher_blip_BlipNative_getScale
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    setScale
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_blip_BlipNative_setScale
        (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mp_rage_launcher_blip_BlipNative_getName
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_blip_BlipNative
 * Method:    setName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_blip_BlipNative_setName
        (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
