/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mp_rage_launcher_player_PlayerNative */

#ifndef _Included_mp_rage_launcher_player_PlayerNative
#define _Included_mp_rage_launcher_player_PlayerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getType
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_destroy
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getDimension
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getDimension
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setDimension
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setDimension
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getPosition
 * Signature: (I)Lmp/rage/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getPosition
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setPosition
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setPosition
        (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getRotation
 * Signature: (I)Lmp/rage/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getRotation
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setRotation
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setRotation
        (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getModel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getModel
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setModel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setModel
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getVelocity
 * Signature: (I)Lmp/rage/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getVelocity
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getAlpha
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getAlpha
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setAlpha
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setAlpha
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    kick
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_kick
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    ban
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_ban
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    outputChatBox
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_outputChatBox
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    notify
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_notify
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    spawn
 * Signature: (IFFFF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_spawn
        (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    playAnimation
 * Signature: (ILjava/lang/String;Ljava/lang/String;FI)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_playAnimation
        (JNIEnv *, jclass, jint, jstring, jstring, jfloat, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    playScenario
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_playScenario
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    stopAnimation
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_stopAnimation
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getClothes
 * Signature: (II)Lmp/rage/api/player/PlayerClothes;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getClothes
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setClothes
 * Signature: (IILmp/rage/api/player/PlayerClothes;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setClothes
        (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getProp
 * Signature: (II)Lmp/rage/api/player/PlayerProperty;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getProp
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setProp
 * Signature: (IILmp/rage/api/player/PlayerProperty;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setProp
        (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    eval
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_eval
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mp_rage_launcher_player_PlayerNative_getName
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setName
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    isAiming
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_launcher_player_PlayerNative_isAiming
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getHeading
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_launcher_player_PlayerNative_getHeading
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setHeading
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setHeading
        (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getMoveSpeed
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_launcher_player_PlayerNative_getMoveSpeed
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getHealth
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_launcher_player_PlayerNative_getHealth
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setHealth
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setHealth
        (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getArmor
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_launcher_player_PlayerNative_getArmor
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setArmor
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setArmor
        (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getAimingAt
 * Signature: (I)Lmp/rage/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getAimingAt
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getPing
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getPing
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getPacketLoss
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_launcher_player_PlayerNative_getPacketLoss
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getKickReason
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mp_rage_launcher_player_PlayerNative_getKickReason
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getIp
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mp_rage_launcher_player_PlayerNative_getIp
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    isJumping
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_launcher_player_PlayerNative_isJumping
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    isInCover
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_launcher_player_PlayerNative_isInCover
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    isEnteringVehicle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_launcher_player_PlayerNative_isEnteringVehicle
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    isLeavingVehicle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_launcher_player_PlayerNative_isLeavingVehicle
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    isClimbing
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_launcher_player_PlayerNative_isClimbing
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    isOnLadder
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_launcher_player_PlayerNative_isOnLadder
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    isReloading
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_launcher_player_PlayerNative_isReloading
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    isInMelee
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_launcher_player_PlayerNative_isInMelee
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getActionString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mp_rage_launcher_player_PlayerNative_getActionString
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getVehicle
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getVehicle
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    putIntoVehicle
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_putIntoVehicle
        (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    removeFromVehicle
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_removeFromVehicle
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getSeat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getSeat
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getEyeColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getEyeColor
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setEyeColor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setEyeColor
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getHairColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getHairColor
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getHairHighlightColor
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getHairHighlightColor
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setHairColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setHairColor
        (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getFaceFeature
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_launcher_player_PlayerNative_getFaceFeature
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setFaceFeature
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setFaceFeature
        (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getHeadBlend
 * Signature: (I)Lmp/rage/api/player/PlayerHeadBlend;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getHeadBlend
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setHeadBlend
 * Signature: (IIIIIIIFFF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setHeadBlend
        (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    updateHeadBlend
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_updateHeadBlend
        (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getHeadOverlay
 * Signature: (II)Lmp/rage/api/player/event/PlayerHeadOverlay;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getHeadOverlay
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setHeadOverlay
 * Signature: (IIIF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setHeadOverlay
        (JNIEnv *, jclass, jint, jint, jint, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getCurrentWeapon
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getCurrentWeapon
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setCurrentWeapon
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setCurrentWeapon
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getCurrentWeaponAmmo
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getCurrentWeaponAmmo
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setCurrentWeaponAmmo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setCurrentWeaponAmmo
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getWeaponAmmo
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getWeaponAmmo
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    setWeaponAmmo
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_setWeaponAmmo
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getWeapons
 * Signature: (I)Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getWeapons
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getWeapon
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_getWeapon
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    giveWeapon
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_giveWeapon
        (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    giveWeapons
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_giveWeapons
        (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    removeWeapon
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_removeWeapon
        (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    removeWeapons
 * Signature: (ILjava/util/List;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_removeWeapons
        (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    removeAllWeapons
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_removeAllWeapons
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    isStreamed
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_launcher_player_PlayerNative_isStreamed
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getStreamed
 * Signature: (I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getStreamed
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getSerial
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mp_rage_launcher_player_PlayerNative_getSerial
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getSocialClubName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mp_rage_launcher_player_PlayerNative_getSocialClubName
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    removeObject
 * Signature: (IIFFFF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_removeObject
        (JNIEnv *, jclass, jint, jint, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    call
 * Signature: (ILjava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_call__ILjava_lang_String_2_3Ljava_lang_String_2
        (JNIEnv *, jclass, jint, jstring, jobjectArray);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    invoke
 * Signature: (IJ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_invoke__IJ_3Ljava_lang_String_2
        (JNIEnv *, jclass, jint, jlong, jobjectArray);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    length
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_length
        (JNIEnv *, jclass);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    count
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mp_rage_launcher_player_PlayerNative_count
        (JNIEnv *, jclass);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getInRange
 * Signature: (FFFFI)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getInRange
        (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    getInDimension
 * Signature: (I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_launcher_player_PlayerNative_getInDimension
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    broadcast
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_broadcast
        (JNIEnv *, jclass, jstring);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    broadcastInRange
 * Signature: (Ljava/lang/String;FFFFI)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_broadcastInRange
        (JNIEnv *, jclass, jstring, jfloat, jfloat, jfloat, jfloat, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    broadcastInDimension
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_broadcastInDimension
        (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    call
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_call__Ljava_lang_String_2_3Ljava_lang_String_2
        (JNIEnv *, jclass, jstring, jobjectArray);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    callInRange
 * Signature: (FFFFILjava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_callInRange
        (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jstring, jobjectArray);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    callInDimension
 * Signature: (ILjava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_callInDimension
        (JNIEnv *, jclass, jint, jstring, jobjectArray);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    invoke
 * Signature: (J[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_invoke__J_3Ljava_lang_String_2
        (JNIEnv *, jclass, jlong, jobjectArray);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    invokeInRange
 * Signature: (FFFFIJ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_invokeInRange
        (JNIEnv *, jclass, jfloat, jfloat, jfloat, jfloat, jint, jlong, jobjectArray);

/*
 * Class:     mp_rage_launcher_player_PlayerNative
 * Method:    invokeInDimension
 * Signature: (IJ[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_launcher_player_PlayerNative_invokeInDimension
        (JNIEnv *, jclass, jint, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
