/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mp_rage_plugin_java_launcher_blip_BlipNative */

#ifndef _Included_mp_rage_plugin_java_launcher_blip_BlipNative
#define _Included_mp_rage_plugin_java_launcher_blip_BlipNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mp_rage_plugin_java_launcher_blip_BlipNative
 * Method:    GetRadius
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_plugin_java_launcher_blip_BlipNative_GetRadius
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_blip_BlipNative
 * Method:    GetMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_blip_BlipNative_GetMode
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_blip_BlipNative
 * Method:    GetColour
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_blip_BlipNative_GetColour
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_blip_BlipNative
 * Method:    SetColour
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_blip_BlipNative_SetColour
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_blip_BlipNative
 * Method:    GetAlpha
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_blip_BlipNative_GetAlpha
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_blip_BlipNative
 * Method:    SetAlpha
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_blip_BlipNative_SetAlpha
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_blip_BlipNative
 * Method:    GetScale
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_plugin_java_launcher_blip_BlipNative_GetScale
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_blip_BlipNative
 * Method:    SetScale
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_blip_BlipNative_SetScale
        (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     mp_rage_plugin_java_launcher_blip_BlipNative
 * Method:    GetName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_mp_rage_plugin_java_launcher_blip_BlipNative_GetName
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_blip_BlipNative
 * Method:    SetName
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_blip_BlipNative_SetName
        (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
