/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative */

#ifndef _Included_de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative
#define _Included_de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative
 * Method:    GetColour
 * Signature: (I)Lde/demofire/ragemultiplayer/api/color/RGBColor;
 */
JNIEXPORT jobject JNICALL Java_de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative_GetColour
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative
 * Method:    SetColour
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative_SetColour
        (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative
 * Method:    GetDirection
 * Signature: (I)Lde/demofire/ragemultiplayer/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative_GetDirection
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative
 * Method:    SetDirection
 * Signature: (ILde/demofire/ragemultiplayer/api/vector/Vector3;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative_SetDirection
        (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative
 * Method:    GetRadius
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative_GetRadius
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative
 * Method:    SetRadius
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative_SetRadius
        (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative
 * Method:    IsVisible
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative_IsVisible
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative
 * Method:    SetVisible
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_checkpoint_CheckpointNative_SetVisible
        (JNIEnv *, jclass, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
