/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mp_rage_plugin_java_launcher_colshape_ColshapeNative */

#ifndef _Included_mp_rage_plugin_java_launcher_colshape_ColshapeNative
#define _Included_mp_rage_plugin_java_launcher_colshape_ColshapeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    IsPointWithin
 * Signature: (ILmp/rage/plugin/java/api/vector/Vector3;)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_IsPointWithin
        (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    GetShapeType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_GetShapeType
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
