/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mp_rage_plugin_java_launcher_colshape_ColshapeNative */

#ifndef _Included_mp_rage_plugin_java_launcher_colshape_ColshapeNative
#define _Included_mp_rage_plugin_java_launcher_colshape_ColshapeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    getType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_getType
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_destroy
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    getDimension
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_getDimension
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    setDimension
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_setDimension
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    getRotation
 * Signature: (I)Lmp/rage/plugin/java/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_getRotation
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    setRotation
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_setRotation
        (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    getModel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_getModel
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    setModel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_setModel
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    getVelocity
 * Signature: (I)Lmp/rage/plugin/java/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_getVelocity
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    getAlpha
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_getAlpha
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    setAlpha
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_setAlpha
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    IsPointWithin
 * Signature: (ILmp/rage/plugin/java/api/vector/Vector3;)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_IsPointWithin
        (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     mp_rage_plugin_java_launcher_colshape_ColshapeNative
 * Method:    GetShapeType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_colshape_ColshapeNative_GetShapeType
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
