/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_demofire_ragemultiplayer_launcher_colshape_ColshapeNative */

#ifndef _Included_de_demofire_ragemultiplayer_launcher_colshape_ColshapeNative
#define _Included_de_demofire_ragemultiplayer_launcher_colshape_ColshapeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_demofire_ragemultiplayer_launcher_colshape_ColshapeNative
 * Method:    IsPointWithin
 * Signature: (ILde/demofire/ragemultiplayer/api/vector/Vector3;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_colshape_ColshapeNative_IsPointWithin
        (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_colshape_ColshapeNative
 * Method:    GetShapeType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_colshape_ColshapeNative_GetShapeType
        (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
