/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_demofire_ragemultiplayer_launcher_EntityNative */

#ifndef _Included_de_demofire_ragemultiplayer_launcher_EntityNative
#define _Included_de_demofire_ragemultiplayer_launcher_EntityNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    getType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_getType
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_destroy
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    getDimension
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_getDimension
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    setDimension
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_setDimension
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    getRotation
 * Signature: (I)Lde/demofire/ragemultiplayer/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_getRotation
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    setRotation
 * Signature: (ILde/demofire/ragemultiplayer/api/vector/Vector3;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_setRotation
        (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    getModel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_getModel
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    setModel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_setModel
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    getVelocity
 * Signature: (I)Lde/demofire/ragemultiplayer/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_getVelocity
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    getAlpha
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_getAlpha
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_EntityNative
 * Method:    setAlpha
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_EntityNative_setAlpha
        (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
