/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mp_rage_plugin_java_launcher_marker_MarkerNative */

#ifndef _Included_mp_rage_plugin_java_launcher_marker_MarkerNative
#define _Included_mp_rage_plugin_java_launcher_marker_MarkerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mp_rage_plugin_java_launcher_marker_MarkerNative
 * Method:    GetColour
 * Signature: (I)Lmp/rage/plugin/java/api/color/RGBColor;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_plugin_java_launcher_marker_MarkerNative_GetColour
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_marker_MarkerNative
 * Method:    SetColour
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_marker_MarkerNative_SetColour
        (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_marker_MarkerNative
 * Method:    GetDirection
 * Signature: (I)Lmp/rage/plugin/java/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_plugin_java_launcher_marker_MarkerNative_GetDirection
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_marker_MarkerNative
 * Method:    SetDirection
 * Signature: (ILmp/rage/plugin/java/api/vector/Vector3;)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_marker_MarkerNative_SetDirection
        (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     mp_rage_plugin_java_launcher_marker_MarkerNative
 * Method:    GetScale
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_mp_rage_plugin_java_launcher_marker_MarkerNative_GetScale
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_marker_MarkerNative
 * Method:    SetScale
 * Signature: (IF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_marker_MarkerNative_SetScale
        (JNIEnv *, jclass, jint, jfloat);

/*
 * Class:     mp_rage_plugin_java_launcher_marker_MarkerNative
 * Method:    IsVisible
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_mp_rage_plugin_java_launcher_marker_MarkerNative_IsVisible
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_marker_MarkerNative
 * Method:    SetVisible
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_marker_MarkerNative_SetVisible
        (JNIEnv *, jclass, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
