/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_demofire_ragemultiplayer_launcher_object_ObjectNative */

#ifndef _Included_de_demofire_ragemultiplayer_launcher_object_ObjectNative
#define _Included_de_demofire_ragemultiplayer_launcher_object_ObjectNative
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
