/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mp_rage_plugin_java_launcher_object_ObjectNative */

#ifndef _Included_mp_rage_plugin_java_launcher_object_ObjectNative
#define _Included_mp_rage_plugin_java_launcher_object_ObjectNative
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
