/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_demofire_ragemultiplayer_launcher_pickup_PickupNative */

#ifndef _Included_de_demofire_ragemultiplayer_launcher_pickup_PickupNative
#define _Included_de_demofire_ragemultiplayer_launcher_pickup_PickupNative
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
