/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mp_rage_plugin_java_launcher_pickup_PickupNative */

#ifndef _Included_mp_rage_plugin_java_launcher_pickup_PickupNative
#define _Included_mp_rage_plugin_java_launcher_pickup_PickupNative
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
