/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mp_rage_plugin_java_launcher_pickup_PickupNative */

#ifndef _Included_mp_rage_plugin_java_launcher_pickup_PickupNative
#define _Included_mp_rage_plugin_java_launcher_pickup_PickupNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    getType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_getType
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    destroy
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_destroy
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    getDimension
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_getDimension
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    setDimension
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_setDimension
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    getRotation
 * Signature: (I)Lmp/rage/plugin/java/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_getRotation
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    setRotation
 * Signature: (IFFF)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_setRotation
        (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    getModel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_getModel
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    setModel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_setModel
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    getVelocity
 * Signature: (I)Lmp/rage/plugin/java/api/vector/Vector3;
 */
JNIEXPORT jobject JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_getVelocity
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    getAlpha
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_getAlpha
        (JNIEnv *, jclass, jint);

/*
 * Class:     mp_rage_plugin_java_launcher_pickup_PickupNative
 * Method:    setAlpha
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_mp_rage_plugin_java_launcher_pickup_PickupNative_setAlpha
        (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
