/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_demofire_ragemultiplayer_launcher_player_PlayerNative */

#ifndef _Included_de_demofire_ragemultiplayer_launcher_player_PlayerNative
#define _Included_de_demofire_ragemultiplayer_launcher_player_PlayerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    kick
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_kick
		(JNIEnv *, jobject, jint, jstring);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    ban
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_ban
		(JNIEnv *, jobject, jint, jstring);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    outputChatBox
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_outputChatBox
		(JNIEnv *, jobject, jint, jstring);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    notify
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_notify
		(JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
