/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_demofire_ragemultiplayer_launcher_player_PlayerNative */

#ifndef _Included_de_demofire_ragemultiplayer_launcher_player_PlayerNative
#define _Included_de_demofire_ragemultiplayer_launcher_player_PlayerNative
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
	* Method:    kick
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_kick
	(JNIEnv *, jobject, jstring);

	/*
	* Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
	* Method:    ban
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_ban
	(JNIEnv *, jobject, jstring);

	/*
	* Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
	* Method:    outputChatBox
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_outputChatBox
	(JNIEnv *, jobject, jstring);

	/*
	* Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
	* Method:    notify
	* Signature: (Ljava/lang/String;)V
	*/
	JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_notify
	(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
