/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_demofire_ragemultiplayer_launcher_player_PlayerNative */

#ifndef _Included_de_demofire_ragemultiplayer_launcher_player_PlayerNative
#define _Included_de_demofire_ragemultiplayer_launcher_player_PlayerNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    getType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_getType
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    getDimension
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_getDimension
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    setDimension
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_setDimension
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    getRotation
 * Signature: (I)Lde/demofire/ragemultiplayer/launcher/Vector3;
 */
JNIEXPORT jobject JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_getRotation
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    setRotation
 * Signature: (ILde/demofire/ragemultiplayer/launcher/Vector3;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_setRotation
        (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    getModel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_getModel
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    setModel
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_setModel
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    getVelocity
 * Signature: (I)Lde/demofire/ragemultiplayer/launcher/Vector3;
 */
JNIEXPORT jobject JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_getVelocity
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    getAlpha
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_getAlpha
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    setAlpha
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_setAlpha
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    kick
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_kick
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    ban
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_ban
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    outputChatBox
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_outputChatBox
        (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_player_PlayerNative
 * Method:    notify
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_player_PlayerNative_notify
        (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
