/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative */

#ifndef _Included_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
#define _Included_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    IsSirenActive
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_IsSirenActive
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    IsHornActive
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_IsHornActive
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    AreHighbeamsActive
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_AreHighbeamsActive
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    AreLightsActive
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_AreLightsActive
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    IsEngineActive
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_IsEngineActive
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    IsRocketBoostActive
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_IsRocketBoostActive
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    IsBrakeActive
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_IsBrakeActive
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    getSteerAngle
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_getSteerAngle
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    getGasPedalState
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_getGasPedalState
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    getEngineHealth
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_getEngineHealth
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    getBodyHealth
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_getBodyHealth
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    getOccupant
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_getOccupant
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    getOccupants
 * Signature: (I)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_getOccupants
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    setOccupant
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_setOccupant
        (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    isLocked
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_isLocked
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    lock
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_lock
        (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    isDead
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_isDead
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    explode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_explode
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    spawn
 * Signature: (ILde/demofire/ragemultiplayer/launcher/Vector3;F)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_spawn
        (JNIEnv *, jclass, jint, jobject, jfloat);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    getMod
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_getMod
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    setMod
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_setMod
        (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    areNeonsEnabled
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_areNeonsEnabled
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    enableNeons
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_enableNeons
        (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    setNeonsColour
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_setNeonsColour
        (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    GetNeonsColour
 * Signature: (I)Lde/demofire/ragemultiplayer/launcher/RGBColor;
 */
JNIEXPORT jobject JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_GetNeonsColour
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    Repair
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_Repair
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    GetColourRGB
 * Signature: (II)Lde/demofire/ragemultiplayer/launcher/RGBColor;
 */
JNIEXPORT jobject JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_GetColourRGB
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    GetColour
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_GetColour
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    GetPaint
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_GetPaint
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    SetColourRGB
 * Signature: (ILde/demofire/ragemultiplayer/launcher/RGBColor;Lde/demofire/ragemultiplayer/launcher/RGBColor;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_SetColourRGB
        (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    SetColour
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_SetColour
        (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    SetPaint
 * Signature: (ILde/demofire/ragemultiplayer/launcher/vehicle/VehiclePaintInfo;Lde/demofire/ragemultiplayer/launcher/vehicle/VehiclePaintInfo;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_SetPaint
        (JNIEnv *, jclass, jint, jobject, jobject);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    GetMaterialType
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_GetMaterialType
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    GetNumberPlate
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_GetNumberPlate
        (JNIEnv *, jclass, jint);

/*
 * Class:     de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative
 * Method:    SetNumberPlate
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_demofire_ragemultiplayer_launcher_vehicle_VehicleNative_SetNumberPlate
        (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
